language: go

go:
- 1.5.3
- 1.6
- tip

sudo: required
dist: trusty

services:
- docker


before_install:
- export REPOSITORY_ROOT=${TRAVIS_BUILD_DIR}
- go get github.com/kisielk/errcheck


before_script:
- cd integration/kafka-docker
- docker-compose up --build -d

script:
- go test -v -race -parallel=1 -timeout=5m github.com/khulnasoft/kafka/...
- go vet github.com/khulnasoft/kafka/...
- errcheck github.com/khulnasoft/kafka/...
- go test -bench '.*' -benchmem -run none github.com/khulnasoft/kafka/...

env:
- WITH_INTEGRATION=true GOMAXPROCS=4

sudo: false
